### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by mr-exz** [mr-exz/whoisondutytoday#64]
ActiveRecord::RecordNotFound: Couldn't find Duty with [WHERE "duties"."channel_id" = ? AND "duties"."enabled" = ?]
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/relation/finder_methods.rb:343:in `raise_record_not_found_exception!'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/relation/finder_methods.rb:109:in `take!'
/myapp/lib/tasks/reminder.rake:8:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/relation/delegation.rb:71:in `each'
/myapp/lib/tasks/reminder.rake:7:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => reminder:remind

**Comment by mr-exz** [comment]
fixed in 0.7.0
